name: build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: always
jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: msrv
      run: |
        msrv=$(cargo metadata --no-deps --format-version 1 |
          jq --raw-output '.packages[] | select(.name=="ndarray-histogram") | .rust_version')
        echo "MSRV=$msrv" >> $GITHUB_ENV
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.MSRV }}
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test
    - name: test-rayon
      run: cargo test --features rayon
    - name: clippy
      run: cargo clippy --all
    - name: doc
      run: cargo doc
    - name: doc-rayon
      run: cargo doc --features rayon
    - name: fmt
      run: cargo fmt --all --check
  nightly:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy, miri
    - name: test
      run: cargo test
    - name: test-rayon
      run: cargo test --features rayon
    - name: clippy
      run: cargo clippy --all
    - name: doc
      run: cargo doc
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-rayon
      run: cargo doc --features rayon
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: fmt
      run: cargo fmt --all --check
    - name: miri
      run: cargo miri test
